services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
      image: adminer
      restart: always
      depends_on:
        - database
      ports:
        - 8080:8080

  datagen:
    image:  python:3.7-slim


networks:
  default:
    name: net_fake_data_gen
    external: true